// <auto-generated> SkSL ports of native/src/EmpiLauncher.App/Styles/Shaders/*.hlsl (the pixel shaders of Oleaje and Térmico). </auto-generated>
namespace EmpiLauncher.Linux.Views;

internal static class Shaders
{
    public const string Oleaje = """

uniform float4 Res;
uniform float4 Clock;
uniform float4 Acc;
uniform float4 Turn;
uniform float4 Aura;
uniform float4 Reveal;
uniform float4 Waves[12];

const float TAU = 6.28318530718;

float2 mod2(float2 x, float y) { return x - y * floor(x / y); }

float caustic(float2 uv, float t)
{
    float2 p = mod2(uv * TAU, TAU) - 250.0;
    float2 i = p;
    float c = 1.0;
    const float inten = 0.005;
    for (int n = 0; n < 5; n++)
    {
        float tt = t * (1.0 - (3.5 / (float(n) + 1.0)));
        i = p + float2(cos(tt - i.x) + sin(tt + i.y), sin(tt - i.y) + cos(tt + i.x));
        c += 1.0 / length(float2(p.x / (sin(i.x + tt) / inten), p.y / (cos(i.y + tt) / inten)));
    }
    c /= 5.0;
    c = 1.17 - pow(abs(c), 1.4);
    return pow(abs(c), 8.0);
}

half4 main(float2 fc)
{
    float2 uv = fc / Res.xy;
    float2 asp = float2(Res.x / Res.y, 1.0);
    float2 pos = uv * asp;

    float2 rv = float2(1.0, 0.0);
    if (Reveal.y > 0.5)
    {
        float edge = mix(1.14, -0.16, Reveal.x) + 0.045 * sin(uv.x * 3.1 + Clock.y * 1.4) + 0.022 * sin(uv.x * 9.0 - Clock.y * 3.3) + 0.009 * sin(uv.x * 27.0 + Clock.y * 5.1);
        float e = uv.y - edge;
        float crest = exp(-e * e / 0.00045);
        float foam = e > 0.0 ? exp(-e * 22.0) * 0.5 : 0.0;
        rv = float2(max(smoothstep(-0.004, 0.004, e), crest * 0.9), crest + foam);
    }

    float2 disp = float2(0.0, 0.02 * rv.y * sin(uv.x * 40.0 + Clock.y * 7.0) * Clock.w);
    float ring = rv.y * 1.1;
    float3 spec = rv.y * 0.4 * (0.5 + 0.5 * cos(TAU * (float3(0.0, 0.33, 0.67) + uv.x * 3.0)));
    for (int k = 0; k < 12; k++)
    {
        float4 w = Waves[k];
        if (w.w > 0.0)
        {
            float2 d = pos - w.xy * asp;
            float dist = length(d);
            float R = w.z * 0.45;
            float fade = w.w * max(0.0, 1.0 - R / 1.9);
            float x = dist - R;
            float front = exp(-x * x / 0.0022) * fade;
            ring += front + (x < 0.0 ? exp(x * 7.0) * 0.3 * fade : 0.0);
            disp += (d / max(dist, 1e-4)) * sin(x * 55.0) * exp(-x * x / 0.012) * 0.018 * fade * Clock.w;
            spec += front * (0.5 + 0.5 * cos(TAU * (float3(0.0, 0.33, 0.67) + x * 9.0)));
        }
    }

    float t = Clock.x * 0.42;
    float2 q = pos + disp;
    float2 r2 = float2(0.866 * q.x - 0.5 * q.y, 0.5 * q.x + 0.866 * q.y);
    float2 cuv = float2(r2.x * 1.15, r2.y * 2.6);
    cuv += 0.10 * float2(sin(q.y * 2.3 + t * 0.8), cos(q.x * 1.9 - t * 0.6));
    float split = 0.013 + 0.035 * ring;
    float cr = caustic(cuv + float2(split, split * 0.4), t);
    float cg = caustic(cuv, t);
    float cb = caustic(cuv - float2(split, split * 0.4), t);

    float2 a = Aura.xy * asp;
    float da = length((pos - a) * float2(0.75, 1.0));
    float aura = exp(-da * da * 2.4);
    float field = mix(0.12, 1.0, aura) * (0.35 + 0.65 * smoothstep(0.1, 0.45, uv.x));
    float amt = Clock.z * field + ring * 0.9;
    float3 base = mix(float3(0.008, 0.016, 0.038), float3(0.03, 0.07, 0.16), aura);
    base += Acc.rgb * aura * 0.12 * (0.4 + Clock.z);
    float3 light = mix(Acc.rgb, float3(1.0, 0.98, 0.94), smoothstep(0.25, 1.0, cg));
    float3 col = base + light * cg * amt * 1.25;
    col += float3(1.0, 0.38, 0.14) * max(0.0, cr - cb) * amt * 2.2;
    col += float3(0.35, 0.55, 1.0) * max(0.0, cb - cr) * amt * 0.7;
    col += spec * 0.35;
    col += Acc.rgb * aura * aura * 0.2 * Clock.z;
    float v = smoothstep(1.3, 0.3, length((uv - float2(0.62, 0.58)) * float2(1.0, 1.2)));
    col *= mix(0.4, 1.0, v);
    col = pow(max(col, float3(0.0)), float3(1.14));

    // the player's colour for the style: the whole palette turns round the grey axis by that angle
    {
        float ca = cos(Turn.x); float sa = sin(Turn.x); float3 k = float3(0.57735);
        col = col * ca + cross(k, col) * sa + k * dot(k, col) * (1.0 - ca);
    }
    return half4(half3(col * rv.x), half(rv.x));
}
""";

    public const string Termico = """

uniform shader Noise;
uniform float4 Res;
uniform float4 Clock;
uniform float4 Acc;
uniform float4 Turn;
uniform float4 Aura;
uniform float4 Reveal;
uniform float4 Waves[12];

// value noise from the texture: 64 cells across it, -1..1; the lookup stays between the first and last texel centres (never in the half texel at the edge)
float noise(float2 p) { return Noise.eval((fract(p / 64.0) * (511.0 / 512.0) + 0.5 / 512.0) * 512.0).r * 2.0 - 1.0; }

float fbm(float2 p)
{
    float s = 0.0, a = 0.5;
    for (int i = 0; i < 3; i++) { s += a * noise(p); p = p * 1.9 + float2(1.7, 9.2); a *= 0.42; }
    return s * 1.6;
}

float form(float2 p, float t)
{
    float2 q = float2(fbm(p + float2(0.0, t)), fbm(p + float2(5.2, 1.3) - t * 0.7));
    float2 r = float2(fbm(p + 1.5 * q + float2(1.7, 9.2) + t * 0.5), fbm(p + 1.5 * q + float2(8.3, 2.8) - t * 0.4));
    return fbm(p + 1.3 * r);
}

float3 thermal(float v)
{
    float3 violet = mix(float3(0.42, 0.25, 0.90), Acc.rgb, 0.55);
    float3 c = float3(0.006, 0.008, 0.016);
    c = mix(c, float3(0.02, 0.10, 0.075), smoothstep(0.16, 0.34, v));
    c = mix(c, violet, smoothstep(0.34, 0.50, v));
    c = mix(c, float3(1.0, 0.33, 0.66), smoothstep(0.52, 0.64, v));
    c = mix(c, float3(1.0, 0.56, 0.30), smoothstep(0.64, 0.76, v));
    c = mix(c, float3(1.0, 0.82, 0.66), smoothstep(0.76, 0.88, v));
    c = mix(c, float3(1.0, 0.97, 0.92), smoothstep(0.88, 1.0, v));
    return c;
}

half4 main(float2 fc)
{
    float2 uv = fc / Res.xy;
    float2 asp = float2(Res.x / Res.y, 1.0);
    float2 pos = uv * asp;

    float2 rv = float2(1.0, 0.0);
    if (Reveal.y > 0.5)
    {
        float d = length(pos - Aura.xy * asp);
        float n = fbm(pos * 2.4 + float2(0.0, Clock.y * 0.2)) * 0.55 + fbm(pos * 7.0 - Clock.y * 0.3) * 0.18;
        float e = mix(-0.4, 1.3, Reveal.x) - (d * 0.6 + n);
        float edge = exp(-e * e / 0.003);
        rv = float2(max(smoothstep(0.0, 0.035, e), edge * 0.9), edge);
    }

    float2 disp = float2(0.0, 0.0);
    float heat = rv.y * 1.25;
    for (int k = 0; k < 12; k++)
    {
        float4 w = Waves[k];
        if (w.w > 0.0)
        {
            float2 d = pos - w.xy * asp;
            float dist = length(d);
            float R = w.z * 0.42;
            float fade = w.w * max(0.0, 1.0 - R / 1.9);
            float x = dist - R;
            heat += exp(-x * x / 0.004) * fade + (x < 0.0 ? exp(x * 6.0) * 0.18 * fade : 0.0);
            disp += (d / max(dist, 1e-4)) * exp(-x * x / 0.01) * 0.05 * fade * Clock.w;
        }
    }

    float t = Clock.x * 0.05;
    float2 p = (pos + disp) * float2(0.62, 0.5);
    float2 a = Aura.xy * asp;
    float da = length((pos - a) * float2(0.7, 1.0));
    float mask = exp(-da * da * 1.7) * (0.3 + 0.7 * smoothstep(0.08, 0.5, uv.x));
    float m0 = 0.5 + (Clock.z - 0.5) * 0.35;
    float2 off = float2(0.009, 0.003);
    float mR = clamp(mask * (m0 + form(p + off, t) * 1.55) - 0.14 + heat * 0.45, 0.0, 1.0);
    float mG = clamp(mask * (m0 + form(p, t) * 1.55) - 0.14 + heat * 0.45, 0.0, 1.0);
    float mB = clamp(mask * (m0 + form(p - off, t) * 1.55) - 0.14 + heat * 0.45, 0.0, 1.0);
    float3 col = float3(thermal(mR).r, thermal(mG).g, thermal(mB).b);
    float hx = (mG - 0.53) / 0.02;
    col += float3(1.0, 0.3, 0.7) * exp(-(hx * hx)) * 0.35;
    float vig = smoothstep(1.35, 0.35, length((uv - float2(0.62, 0.55)) * float2(1.0, 1.2)));
    col *= mix(0.35, 1.0, vig);

    // the player's colour for the style: the whole palette turns round the grey axis by that angle
    {
        float ca = cos(Turn.x); float sa = sin(Turn.x); float3 k = float3(0.57735);
        col = col * ca + cross(k, col) * sa + k * dot(k, col) * (1.0 - ca);
    }
    return half4(half3(col * rv.x), half(rv.x));
}
""";
}
